DROP TABLE if exists user_pass;
DROP TABLE if exists user_token;
DROP TABLE if exists hotel_review;
DROP TABLE if exists hotel;
DROP TABLE if exists user_info;

CREATE TABLE if not exists USER_INFO(ID SERIAL PRIMARY KEY, FIRST_NAME VARCHAR(255), LAST_NAME VARCHAR(255), MAIL VARCHAR(255), DATE_OF_BIRTH DATE, SEX VARCHAR(64));
CREATE UNIQUE INDEX if not exists UI_USER_INFO_MAIL ON USER_INFO(MAIL);

CREATE TABLE if not exists USER_PASS(ID SERIAL PRIMARY KEY, ID_USER INT references USER_INFO(ID),PASS VARCHAR(255));

CREATE TABLE if not exists USER_TOKEN(ID SERIAL PRIMARY KEY, ID_USER INT references USER_INFO(ID), TOKEN VARCHAR(255));

CREATE TABLE if not exists HOTEL(ID SERIAL PRIMARY KEY, NAME VARCHAR(255), DESCRIPTION VARCHAR(255), COUNTRY VARCHAR(255), CITY VARCHAR(255), STAR INT, WEBSITE VARCHAR(255));
CREATE UNIQUE INDEX if not exists UI_HOTEL_NAME ON HOTEL(NAME);

CREATE TABLE if not exists HOTEL_REVIEW(ID SERIAL PRIMARY KEY, ID_USER SERIAL constraint ID_USER references USER_INFO(ID) on update cascade on delete cascade, ID_HOTEL SERIAL constraint ID_HOTEL references HOTEL(ID) on update cascade on delete cascade, DATE_OF_VISIT DATE, RATING INT, DESCRIPTION VARCHAR(255));


INSERT INTO user_info (FIRST_NAME, LAST_NAME, MAIL, DATE_OF_BIRTH, SEX) VALUES ('Артем', 'Луньков', 'mmmoonnn@mail.ru', '1988-04-10', 'Мужской');

INSERT INTO HOTEL (NAME, DESCRIPTION, COUNTRY, CITY, STAR, WEBSITE) VALUES ('zZooMm', 'well yes zZooMm', 'Russia', 'Bryansk', 6, ' https://www.jetbrains.com/');
INSERT INTO HOTEL (NAME, DESCRIPTION, COUNTRY, CITY, STAR, WEBSITE) VALUES ('zZooMm 2', 'well yes zZooMm 2', 'Russia', 'Bryansk', 5, 'zZooMm2.ru');
INSERT INTO HOTEL (NAME, DESCRIPTION, COUNTRY, CITY, STAR, WEBSITE) VALUES ('zZooMm 3', 'A nu da', 'Russia', 'Bryansk 123', 4, 'https://freemarker.apache.org/');
INSERT INTO HOTEL (NAME, DESCRIPTION, COUNTRY, CITY, STAR, WEBSITE) VALUES ('zZooMm 4', 'Test description', 'Russia', 'Bryansk 2', 3, 'zZooMm2.ru');
INSERT INTO HOTEL (NAME, DESCRIPTION, COUNTRY, CITY, STAR, WEBSITE) VALUES ('zZooMm 5', 'well yes zZooMm 2', 'Russia', 'Bryansk 4', 1, 'https://stackoverflow.com/');

INSERT INTO HOTEL_REVIEW (ID_USER, ID_HOTEL, DATE_OF_VISIT, RATING, DESCRIPTION) VALUES (1, 1, '2019-04-10', 10, 'Top');
INSERT INTO HOTEL_REVIEW (ID_USER, ID_HOTEL, DATE_OF_VISIT, RATING, DESCRIPTION) VALUES (1, 1, '2016-04-10', 9, 'Comment');

INSERT INTO HOTEL_REVIEW (ID_USER, ID_HOTEL, DATE_OF_VISIT, RATING, DESCRIPTION) VALUES (1, 2, '2019-04-10', 3, 'DNO');
INSERT INTO HOTEL_REVIEW (ID_USER, ID_HOTEL, DATE_OF_VISIT, RATING, DESCRIPTION) VALUES (1, 2, '2016-04-10', 1, 'fu fu fu');