
CREATE TABLE if not exists USER_INFO(ID SERIAL PRIMARY KEY, FIRSTNAME VARCHAR(255), LASTNAME VARCHAR(255), MAIL VARCHAR(255), DATEOFBIRTH DATE, SEX VARCHAR(64));
CREATE UNIQUE INDEX if not exists UI_USER_INFO_MAIL ON USER_INFO(MAIL);

CREATE TABLE if not exists USER_PASS(ID SERIAL PRIMARY KEY, IDUSER INT references USER_INFO(ID),PASS VARCHAR(255));

CREATE TABLE if not exists USER_TOKEN(ID SERIAL PRIMARY KEY, IDUSER INT references USER_INFO(ID), TOKEN VARCHAR(255));

CREATE TABLE if not exists HOTEL(ID SERIAL PRIMARY KEY, NAME VARCHAR(255), DESCRIPTION VARCHAR(255), COUNTRY VARCHAR(255), CITY VARCHAR(255), STAR INT, WEBSITE VARCHAR(255));
CREATE UNIQUE INDEX if not exists UI_HOTEL_NAME ON HOTEL(NAME);

CREATE TABLE if not exists HOTEL_REVIEW(ID SERIAL PRIMARY KEY, USER_ID SERIAL constraint IDUSER references USER_INFO(ID) on update cascade on delete cascade, HOTEL_ID SERIAL constraint IDHOTEL references HOTEL(ID) on update cascade on delete cascade, DATEOFVISIT DATE, RATING INT, DESCRIPTION VARCHAR(255));